/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type CreateCustomer struct {
	// Given Name or First Name
	FirstName string `json:"firstName"`
	// Middle Name
	MiddleName string `json:"middleName,omitempty"`
	// Surname or Last Name
	LastName string `json:"lastName"`
	// Name Customer is preferred to be called
	NickName string `json:"nickName,omitempty"`
	// Customers name suffix. \"Jr\", \"PH.D.\"
	Suffix string `json:"suffix,omitempty"`
	// Legal date of birth
	BirthDate time.Time `json:"birthDate"`
	// Primary email address of customer name@domain.com
	Email string `json:"email"`
	// Customer Social Security Number (SSN)
	SSN       string            `json:"SSN,omitempty"`
	Phones    []CreatePhone     `json:"phones,omitempty"`
	Addresses []CreateAddress   `json:"addresses"`
	Metadata  map[string]string `json:"metadata,omitempty"`
}
