/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CustomerMetadata struct {
	Metadata map[string]string `json:"metadata"`
}
