/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Address struct {
	Type string `json:"type,omitempty"`
	// First line of the address
	Address1 string `json:"address1,omitempty"`
	// Second line of the address
	Address2 string `json:"address2,omitempty"`
	City     string `json:"city,omitempty"`
	// two charcer code of US state
	State      string `json:"state,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
	Country    string `json:"country,omitempty"`
	// Address has been validated for customer
	Validated bool `json:"validated,omitempty"`
	// Address is currently being used for customer
	Active bool `json:"active,omitempty"`
}
