/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Customer struct {
	// The unique identifier for the customer who owns the account
	ID string `json:"ID,omitempty"`
	// Given Name or First Name
	FirstName string `json:"firstName,omitempty"`
	// Middle Name
	MiddleName string `json:"middleName,omitempty"`
	// Surname or Last Name
	LastName string `json:"lastName,omitempty"`
	// Name Customer is preferred to be called
	NickName string `json:"nickName,omitempty"`
	// Customers name suffix. \"Jr\", \"PH.D.\"
	Suffix string `json:"suffix,omitempty"`
	// Legal date of birth
	BirthDate time.Time `json:"birthDate,omitempty"`
	// State of the customer
	Status string `json:"status,omitempty"`
	// Primary email address of customer name@domain.com
	Email     string    `json:"email,omitempty"`
	Phones    []Phone   `json:"phones,omitempty"`
	Addresses []Address `json:"addresses,omitempty"`
	// Map of unique keys associated to values to act as foreign key relationships or arbitrary data associated to a Customer.
	Metadata  map[string]string `json:"metadata,omitempty"`
	CreatedAt time.Time         `json:"createdAt,omitempty"`
	// Last time the object was modified
	LastModified time.Time `json:"lastModified,omitempty"`
}
