/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Phone struct for Phone
type Phone struct {
	// phone number
	Number string `json:"number,omitempty"`
	// phone number has been validated to connect with customer
	Valid bool   `json:"valid,omitempty"`
	Type  string `json:"type,omitempty"`
}
