/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Disclaimer struct for Disclaimer
type Disclaimer struct {
	// The unique identifier for this Disclaimer
	ID string `json:"ID,omitempty"`
	// Text that user must accept
	Text string `json:"text,omitempty"`
}
