/*
 * Customers API
 *
 * Customers ...
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CustomerError struct for CustomerError
type CustomerError struct {
	// An error message describing the problem intended for humans.
	Error string `json:"error"`
}
