/*
 * Customers API
 *
 * Customers focuses on solving authentic identification of humans who are legally able to hold and transfer currency within the US. Primarily this project solves [Know Your Customer](https://en.wikipedia.org/wiki/Know_your_customer) (KYC), [Customer Identification Program](https://en.wikipedia.org/wiki/Customer_Identification_Program) (CIP), [Office of Foreign Asset Control](https://www.treasury.gov/about/organizational-structure/offices/Pages/Office-of-Foreign-Assets-Control.aspx) (OFAC) checks and verification workflows to comply with US federal law and ensure authentic transfers. Customers has an objective to be a service for detailed due diligence on individuals and companies for Financial Institutions and services in a modernized and extensible way.  Customer phone numbers and addresses are stored and partially used in KYC/OFAC validation. Arbitrary key/value pairs can be stored for a Customer. Documents and Disclaimers, and their acknowledgement are also stored under a Customer as they're accepted. Bank Accounts, which can be validated with micro-deposits currently, are stored under each Customer.  ![](https://raw.githubusercontent.com/adamdecaf/customers/create-accounts/docs/images/customer.png)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// NaicsCode NAICS Code (https://docs.google.com/spreadsheets/d/1erIdqoy60JwLAnpb91EfoJV5YrXDnbwSaA-aqcBlw48/edit#gid=1627409140)
type NaicsCode string

// List of NAICSCode
const (
	NAICSCODE__11 NaicsCode = "11"
	NAICSCODE__21 NaicsCode = "21"
	NAICSCODE__22 NaicsCode = "22"
	NAICSCODE__23 NaicsCode = "23"
	NAICSCODE__31 NaicsCode = "31"
	NAICSCODE__32 NaicsCode = "32"
	NAICSCODE__33 NaicsCode = "33"
	NAICSCODE__42 NaicsCode = "42"
	NAICSCODE__44 NaicsCode = "44"
	NAICSCODE__45 NaicsCode = "45"
	NAICSCODE__48 NaicsCode = "48"
	NAICSCODE__49 NaicsCode = "49"
	NAICSCODE__51 NaicsCode = "51"
	NAICSCODE__52 NaicsCode = "52"
	NAICSCODE__53 NaicsCode = "53"
	NAICSCODE__54 NaicsCode = "54"
	NAICSCODE__55 NaicsCode = "55"
	NAICSCODE__56 NaicsCode = "56"
	NAICSCODE__61 NaicsCode = "61"
	NAICSCODE__62 NaicsCode = "62"
	NAICSCODE__71 NaicsCode = "71"
	NAICSCODE__72 NaicsCode = "72"
	NAICSCODE__81 NaicsCode = "81"
	NAICSCODE__92 NaicsCode = "92"
	NAICSCODE__99 NaicsCode = "99"
)
